# Generated by Django 5.2.4 on 2025-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='message',
        ),
        migrations.AddField(
            model_name='submission',
            name='email',
            field=models.EmailField(default='info@globyz.com', max_length=254),
            preserve_default=False,
        ),
    ]
